In [127]:
import pandas as pd

## read data

In [129]:
data_train = pd.read_csv(r"C:\Users\hawra\OneDrive\Desktop\project\deep learning\RNN\training.1600000.processed.noemoticon.csv", encoding="latin1")
data_train

,polarity of tweet,id of the tweet,date of the tweet,query,user,text of the tweet
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...
1048567,4,1960186342,Fri May 29 07:33:44 PDT 2009,NO_QUERY,Madelinedugganx,My GrandMa is making Dinenr with my Mum
1048568,4,1960186409,Fri May 29 07:33:43 PDT 2009,NO_QUERY,OffRoad_Dude,Mid-morning snack time... A bowl of cheese noo...
1048569,4,1960186429,Fri May 29 07:33:44 PDT 2009,NO_QUERY,Falchion,@ShaDeLa same here say it like from the Termi...
1048570,4,1960186445,Fri May 29 07:33:44 PDT 2009,NO_QUERY,jonasobsessedx,@DestinyHope92 im great thaanks wbuu?
1048571,4,1960186607,Fri May 29 07:33:45 PDT 2009,NO_QUERY,sugababez,cant wait til her date this weekend

In [130]:
data_train.shape

(1048572, 6)

## drop columns

In [132]:
data_train.columns

Index(['polarity of tweet ', 'id of the tweet', 'date of the tweet', 'query',
       'user', 'text of the tweet '],
      dtype='object')

In [133]:
data_train.drop(['user','query','date of the tweet' , 'id of the tweet',] ,axis=1 , inplace=True)
data_train

         polarity of tweet                                  text of the tweet
0                         0  is upset that he can't update his Facebook by ...
1                         0  @Kenichan I dived many times for the ball. Man...
2                         0    my whole body feels itchy and like its on fire
3                         0  @nationwideclass no, it's not behaving at all....
4                         0                      @Kwesidei not the whole crew
...                     ...                                                ...
1048567                   4           My GrandMa is making Dinenr with my Mum
1048568                   4  Mid-morning snack time... A bowl of cheese noo...
1048569                   4  @ShaDeLa same here  say it like from the Termi...
1048570                   4             @DestinyHope92 im great thaanks  wbuu?
1048571                   4               cant wait til her date this weekend

[1048572 rows x 2 columns]

In [134]:
data_train.isnull().sum()

polarity of tweet     0
text of the tweet     0
dtype: int64

## tokenizing

In [136]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [137]:
# Extract sentences
data_train_label = data_train.iloc[:, 0].astype(str).tolist()
data_train_feture = data_train.iloc[:, 1].astype(str).tolist()

In [138]:
tk = Tokenizer(filters='' , lower=True , )
tk.fit_on_texts(data_train_feture)

In [139]:
tk.index_word

{1: 'i',
 2: 'to',
 3: 'the',
 4: 'a',
 5: 'my',
 6: 'and',
 7: 'is',
 8: 'in',
 9: 'for',
 10: 'you',
 11: 'it',
 12: 'of',
 13: 'on',
 14: 'so',
 15: 'have',
 16: 'but',
 17: 'me',
 18: "i'm",
 19: 'that',
 20: 'just',
 21: 'not',
 22: 'at',
 23: 'be',
 24: 'was',
 25: 'with',
 26: 'this',
 27: 'get',
 28: 'no',
 29: 'up',
 30: 'like',
 31: 'all',
 32: 'go',
 33: 'out',
 34: 'are',
 35: 'now',
 36: "it's",
 37: 'going',
 38: 'good',
 39: 'got',
 40: 'day',
 41: 'do',
 42: 'work',
 43: '-',
 44: "don't",
 45: 'from',
 46: 'back',
 47: 'im',
 48: 'your',
 49: "can't",
 50: 'really',
 51: 'had',
 52: 'too',
 53: 'am',
 54: 'about',
 55: 'want',
 56: 'still',
 57: 'what',
 58: 'miss',
 59: 'we',
 60: 'will',
 61: 'its',
 62: 'one',
 63: 'u',
 64: 'love',
 65: 'time',
 66: 'know',
 67: 'can',
 68: 'see',
 69: 'when',
 70: 'some',
 71: 'think',
 72: 'if',
 73: 'how',
 74: 'today',
 75: 'need',
 76: 'last',
 77: 'they',
 78: '&amp;',
 79: '2',
 80: 'has',
 81: 'as',
 82: 'feel',
 83: 'been',
 84: 'wish',
 85: 'an',
 86: 'lol',
 87: 'oh',
 88: 'new',
 89: 'more',
 90: 'off',
 91: 'home',
 92: 'sad',
 93: 'much',
 94: 'there',
 95: 'why',
 96: 'only',
 97: 'hope',
 98: 'he',
 99: 'bad',
 100: 'her',
 101: 'or',
 102: 'then',
 103: 'hate',
 104: 'here',
 105: 'night',
 106: 'would',
 107: 'sorry',
 108: 'well',
 109: 'very',
 110: 'getting',
 111: "didn't",
 112: 'by',
 113: 'gonna',
 114: 'make',
 115: 'did',
 116: 'she',
 117: 'could',
 118: 'right',
 119: 'come',
 120: "i'll",
 121: 'twitter',
 122: 'sleep',
 123: 'tomorrow',
 124: 'even',
 125: 'dont',
 126: 'over',
 127: "i've",
 128: 'cant',
 129: 'morning',
 130: 'great',
 131: 'way',
 132: 'wanna',
 133: 'never',
 134: 'should',
 135: 'happy',
 136: 'thanks',
 137: "that's",
 138: 'them',
 139: 'after',
 140: 'were',
 141: 'watching',
 142: 'again',
 143: 'next',
 144: 'being',
 145: 'feeling',
 146: '...',
 147: 'school',
 148: 'people',
 149: 'better',
 150: 'take',
 151: 'having',
 152: 'sick',
 153: 'down',
 154: 'find',
 155: 'working',
 156: 'any',
 157: 'little',
 158: 'fun',
 159: 'his',
 160: 'long',
 161: 'him',
 162: 'haha',
 163: 'wait',
 164: 'though',
 165: '4',
 166: 'because',
 167: 'nice',
 168: 'week',
 169: "you're",
 170: 'bed',
 171: 'another',
 172: 'who',
 173: 'it.',
 174: 'our',
 175: 'doing',
 176: 'days',
 177: 'where',
 178: 'watch',
 179: 'than',
 180: 'went',
 181: '3',
 182: 'first',
 183: 'trying',
 184: '.',
 185: 'missed',
 186: '!',
 187: 'tonight',
 188: 'say',
 189: 'always',
 190: "won't",
 191: 'lost',
 192: 'tired',
 193: "doesn't",
 194: 'phone',
 195: 'looking',
 196: 'before',
 197: 'made',
 198: 'already',
 199: 'today.',
 200: 'please',
 201: 'ready',
 202: 'now.',
 203: 'something',
 204: 'someone',
 205: 'left',
 206: 'hours',
 207: 'me.',
 208: 'weekend',
 209: 'into',
 210: 'show',
 211: 'x',
 212: 'best',
 213: 'thing',
 214: 'let',
 215: 'damn',
 216: 'guess',
 217: 'sure',
 218: 'look',
 219: 'poor',
 220: 'ur',
 221: 'yeah',
 222: 'thought',
 223: 'thank',
 224: '@',
 225: 'life',
 226: 'done',
 227: 'missing',
 228: 'away',
 229: 'old',
 230: 'nothing',
 231: 'hey',
 232: 'us',
 233: 'until',
 234: 'pretty',
 235: 'maybe',
 236: 'keep',
 237: 'does',
 238: 'friends',
 239: 'same',
 240: 'since',
 241: 'early',
 242: 'looks',
 243: 'makes',
 244: 'rain',
 245: 'big',
 246: 'other',
 247: 'everyone',
 248: 'hear',
 249: 'things',
 250: 'two',
 251: 'start',
 252: 'help',
 253: 'coming',
 254: 'house',
 255: 'gotta',
 256: "haven't",
 257: 'bit',
 258: 'waiting',
 259: 'woke',
 260: 'n',
 261: 'live',
 262: 'hard',
 263: 'guys',
 264: 'might',
 265: 'ever',
 266: 'sucks',
 267: 'saw',
 268: 'while',
 269: 'tell',
 270: 'those',
 271: 'bored',
 272: "isn't",
 273: 'hot',
 274: '..',
 275: 'try',
 276: 'soon',
 277: 'such',
 278: 'wanted',
 279: 'yet',
 280: 'said',
 281: 'many',
 282: 'play',
 283: 'omg',
 284: 'without',
 285: 'few',
 286: 'weather',
 287: 'finally',
 288: 'thats',
 289: 'summer',
 290: 'their',
 291: 'found',
 292: '?',
 293: 'till',
 294: 'ok',
 295: 'man',
 296: 'leave',
 297: '1',
 298: 'head',
 299: 'must',
 300: 'car',
 301: 'put',
 302: 'didnt',
 303: 'actually',
 304: 'hurts',
 305: 'cold',
 306: 'believe',
 307: 'stupid',
 308: 'late',
 309: 'give',
 310: 'may',
 311: 'gone',
 312: 'day.',
 313: 'it!',
 314: 'making',
 315: 'stop',
 316: 'friend',
 317: '&lt;3',
 318: 'year',
 319: 'baby',
 320: 'talk',
 321: 'tweet',
 322: "he's",
 323: 'almost',
 324: 'least',
 325: 'around',
 326: 'call',
 327: 'also',
 328: 'sun',
 329: "i'd",
 330: 'use',
 331: 'lot',
 332: 'movie',
 333: 'wants',
 334: 'myself',
 335: 'mom',
 336: '5',
 337: 'read',
 338: 'anything',
 339: 'follow',
 340: 'glad',
 341: 'iphone',
 342: 'yes',
 343: 'work.',
 344: 'awesome',
 345: 'most',
 346: 'you.',
 347: 'anyone',
 348: 'hour',
 349: 'these',
 350: 'cause',
 351: 'too.',
 352: 'stuff',
 353: 'which',
 354: 'game',
 355: 'sounds',
 356: 'thinking',
 357: 'eat',
 358: 'end',
 359: 'cool',
 360: 'totally',
 361: 'probably',
 362: 'able',
 363: 'aww',
 364: ',',
 365: 'you!',
 366: 'stuck',
 367: 'buy',
 368: 'stay',
 369: 'every',
 370: 'sooo',
 371: 'forward',
 372: 'whole',
 373: 'through',
 374: 'girl',
 375: 'ugh',
 376: 'well,',
 377: 'god',
 378: 'forgot',
 379: 'ill',
 380: 'playing',
 381: 'party',
 382: 'finished',
 383: "couldn't",
 384: "wasn't",
 385: "there's",
 386: 'kinda',
 387: 'mean',
 388: 'everything',
 389: 'wont',
 390: 'job',
 391: 'far',
 392: 'leaving',
 393: 'hair',
 394: 'me!',
 395: 'enough',
 396: 'took',
 397: 'r',
 398: 'yesterday',
 399: 'tried',
 400: 'lol.',
 401: 'monday',
 402: 'ya',
 403: ';)',
 404: 'taking',
 405: 'feels',
 406: 'came',
 407: 'says',
 408: 'sunday',
 409: 'wrong',
 410: "she's",
 411: 'shit',
 412: 'seen',
 413: 'mine',
 414: 'check',
 415: 'tomorrow.',
 416: 'half',
 417: 'friday',
 418: 'birthday',
 419: 'headache',
 420: 'listening',
 421: 'food',
 422: 'seems',
 423: "we're",
 424: 'exam',
 425: 'real',
 426: 'night.',
 427: 'again.',
 428: 'needs',
 429: "what's",
 430: 'cuz',
 431: 'music',
 432: 'later',
 433: 'sitting',
 434: 'hurt',
 435: 'money',
 436: 'used',
 437: 'song',
 438: 'family',
 439: 'outside',
 440: 'super',
 441: 'tho',
 442: 'beautiful',
 443: 'free',
 444: 'up.',
 445: 'weeks',
 446: 'yeah,',
 447: 'home.',
 448: 'luck',
 449: 'today,',
 450: 'soo',
 451: 'day!',
 452: 'xx',
 453: 'busy',
 454: 'it,',
 455: 'times',
 456: 'amazing',
 457: 'raining',
 458: 'broke',
 459: 'too!',
 460: 'lunch',
 461: 'excited',
 462: 'eating',
 463: 'world',
 464: 'dad',
 465: 'though.',
 466: "they're",
 467: 'hi',
 468: 'hit',
 469: 'room',
 470: 'class',
 471: 'internet',
 472: 'anymore',
 473: 'time.',
 474: '=',
 475: 'sad.',
 476: 'computer',
 477: '10',
 478: 'enjoy',
 479: 'wake',
 480: 'video',
 481: 'now,',
 482: 'heard',
 483: 'following',
 484: 'me,',
 485: 'hopefully',
 486: 'full',
 487: 'tonight.',
 488: 'told',
 489: '6',
 490: 'tv',
 491: 'watched',
 492: 'out.',
 493: 'send',
 494: 'wow',
 495: 'both',
 496: 'alone',
 497: 'else',
 498: 'gets',
 499: 'dinner',
 500: 'starting',
 501: 'sore',
 502: 'started',
 503: 'coffee',
 504: 'lots',
 505: 'fuck',
 506: 'sleep.',
 507: 'place',
 508: 'dog',
 509: 'til',
 510: 'b',
 511: 'that.',
 512: 'rest',
 513: 'talking',
 514: 'fucking',
 515: 'kids',
 516: 'seeing',
 517: 'hell',
 518: 'meet',
 519: 'run',
 520: 'good.',
 521: 'goes',
 522: 'you?',
 523: 'yay',
 524: 'own',
 525: 'you,',
 526: 'pain',
 527: 'morning.',
 528: 'saturday',
 529: 'guy',
 530: 'office',
 531: 'today!',
 532: 'remember',
 533: 'boring',
 534: 'cry',
 535: 'heart',
 536: 'quite',
 537: 'years',
 538: 'called',
 539: 'face',
 540: 'kind',
 541: 'awww',
 542: 'win',
 543: 'tweets',
 544: 'news',
 545: 'study',
 546: 'post',
 547: 'soooo',
 548: 'hoping',
 549: 'w/',
 550: 'crazy',
 551: 'either',
 552: 'reading',
 553: 'lovely',
 554: 'pic',
 555: 'mad',
 556: '!!',
 557: 'part',
 558: 'seem',
 559: 'worst',
 560: 'once',
 561: 'idea',
 562: 'boo',
 563: 'wishing',
 564: 'change',
 565: 'supposed',
 566: 'now!',
 567: 'asleep',
 568: 'yes,',
 569: 'finish',
 570: 'haha.',
 571: 'beach',
 572: 'here.',
 573: 'bed.',
 574: 'bring',
 575: 'ive',
 576: 'drive',
 577: 'oh,',
 578: 'cut',
 579: 'open',
 580: 'heading',
 581: 'bought',
 582: 'season',
 583: 'died',
 584: 'sleeping',
 585: 'break',
 586: 'sweet',
 587: 'funny',
 588: 'trip',
 589: '8',
 590: 'sunny',
 591: 'loved',
 592: 'book',
 593: '+',
 594: 'means',
 595: 'dead',
 596: 'update',
 597: 'well.',
 598: 'name',
 599: 'running',
 600: 'awake',
 601: 'doesnt',
 602: '7',
 603: 'followers',
 604: 'move',
 605: 'no,',
 606: 'fall',
 607: 'bout',
 608: 'cute',
 609: 'online',
 610: 'ass',
 611: 'fell',
 612: 'shopping',
 613: 'ate',
 614: 'exams',
 615: 'red',
 616: 'girls',
 617: 'instead',
 618: 'throat',
 619: 'okay',
 620: 'walk',
 621: 'laptop',
 622: 'care',
 623: '@tommcfly',
 624: 'minutes',
 625: 'reply',
 626: 'couple',
 627: 'bye',
 628: 'goin',
 629: 'broken',
 630: 'happened',
 631: 'text',
 632: 'due',
 633: 'studying',
 634: 'picture',
 635: 'me?',
 636: 'person',
 637: 'welcome',
 638: 'comes',
 639: 'write',
 640: 'concert',
 641: 'high',
 642: 'homework',
 643: 'seriously',
 644: 'link',
 645: 'turn',
 646: 'boy',
 647: 'lucky',
 648: 'ice',
 649: 'past',
 650: 'hahaha',
 651: '@mileycyrus',
 652: 'week.',
 653: 'aw',
 654: 'eyes',
 655: 'work,',
 656: 'less',
 657: 'mind',
 658: 'sound',
 659: 'upset',
 660: 'day,',
 661: 'ipod',
 662: 'hungry',
 663: "aren't",
 664: 'cannot',
 665: 'ago',
 666: 'crap',
 667: 'pics',
 668: 'ah',
 669: 'xd',
 670: 'clean',
 671: 'using',
 672: 'air',
 673: 'final',
 674: 'stomach',
 675: 'ppl',
 676: 'facebook',
 677: '@ddlovato',
 678: 'unfortunately',
 679: ':/',
 680: 'soon.',
 681: 'there.',
 682: 'hang',
 683: 'definitely',
 684: "you'll",
 685: 'sister',
 686: 'blog',
 687: 'knew',
 688: 'catch',
 689: 'horrible',
 690: 'tickets',
 691: 'hello',
 692: 'saying',
 693: 'close',
 694: 'suck',
 695: ')',
 696: 'lil',
 697: 'tummy',
 698: 'it?',
 699: 'test',
 700: 'set',
 701: 'driving',
 702: 'la',
 703: 'gave',
 704: 'three',
 705: 'scared',
 706: 'english',
 707: "wouldn't",
 708: 'favorite',
 709: "we'll",
 710: 'hates',
 711: 'moving',
 712: "mother's",
 713: 'drink',
 714: 'rather',
 715: 'top',
 716: 'month',
 717: 'cat',
 718: 'dream',
 719: 'ask',
 720: 'apparently',
 721: 'goodnight',
 722: 'sometimes',
 723: 'months',
 724: 'longer',
 725: 'up!',
 726: 'second',
 727: 'water',
 728: 'tired.',
 729: 'havent',
 730: 'spent',
 731: 'listen',
 732: 'breakfast',
 733: 'under',
 734: 'whats',
 735: 'pay',
 736: 'shame',
 737: 'brother',
 738: 'yay!',
 739: 'enjoying',
 740: 'fail',
 741: 'site',
 742: 'email',
 743: ':',
 744: 'reason',
 745: 'slept',
 746: 'ha',
 747: 'da',
 748: 'mothers',
 749: 'sucks.',
 750: 'sent',
 751: 'ones',
 752: 'understand',
 753: 'wonder',
 754: 'meeting',
 755: 'true',
 756: 'problem',
 757: 'one.',
 758: 'jealous',
 759: 'during',
 760: 'june',
 761: '1st',
 762: 'sick.',
 763: 'spend',
 764: 'cleaning',
 765: 'happen',
 766: 'mood',
 767: 'all.',
 768: 'up,',
 769: 'keeps',
 770: 'visit',
 771: 'body',
 772: 'killing',
 773: 'morning!',
 774: 'worth',
 775: 'thanks!',
 776: 'wondering',
 777: 'fun!',
 778: 'no!',
 779: '....',
 780: 'side',
 781: 'slow',
 782: 'town',
 783: 'rainy',
 784: 'xxx',
 785: 'isnt',
 786: 'fan',
 787: 'tour',
 788: 'writing',
 789: 'mum',
 790: 'pick',
 791: 'ride',
 792: 'college',
 793: 'yea',
 794: 'city',
 795: 'works',
 796: 'star',
 797: 'worse',
 798: 'short',
 799: 'know.',
 800: 'sorry.',
 801: 'felt',
 802: 'huge',
 803: 'sold',
 804: 'weekend.',
 805: 'chance',
 806: 'them.',
 807: 'know,',
 808: 'figure',
 809: 'flight',
 810: 'store',
 811: 'kill',
 812: 'except',
 813: 'night,',
 814: 'black',
 815: 'fix',
 816: 'do.',
 817: 'ok,',
 818: 'course',
 819: 'boys',
 820: 'add',
 821: 'parents',
 822: 'idk',
 823: 'looked',
 824: 'time!',
 825: 'gym',
 826: 'bus',
 827: 'lol!',
 828: 'again!',
 829: 'weird',
 830: 'tomorrow!',
 831: 'crying',
 832: 'sadly',
 833: 'won',
 834: 'train',
 835: 'thinks',
 836: 'lmao',
 837: 'ugh.',
 838: 'bad.',
 839: 'forget',
 840: 'night!',
 841: 'loves',
 842: 'wear',
 843: 'drinking',
 844: 'shower',
 845: 'realized',
 846: 'flu',
 847: 'lonely',
 848: 'much.',
 849: 'dance',
 850: 'holiday',
 851: 'wonderful',
 852: 'save',
 853: 'sat',
 854: 'youtube',
 855: 'tea',
 856: 'back.',
 857: 'cos',
 858: 'chocolate',
 859: '!!!',
 860: 'dear',
 861: 'nite',
 862: 'fine',
 863: 'plus',
 864: 'fun.',
 865: 'yet.',
 866: 'especially',
 867: 'waking',
 868: '12',
 869: 'plans',
 870: 'sleepy',
 871: 'wishes',
 872: 'church',
 873: 'london',
 874: 'bet',
 875: 'work!',
 876: 'mac',
 877: 'officially',
 878: 'page',
 879: 'movies',
 880: 'afternoon',
 881: 'inside',
 882: '9',
 883: '30',
 884: 'good!',
 885: 'goodbye',
 886: 'loving',
 887: 'turned',
 888: '20',
 889: 'fast',
 890: 'cream',
 891: "let's",
 892: 'nap',
 893: 'taken',
 894: 'out!',
 895: 'meant',
 896: "you've",
 897: 'too,',
 898: 'hand',
 899: 'near',
 900: 'together',
 901: "it'll",
 902: 'bloody',
 903: 'soon!',
 904: 'school.',
 905: 'lose',
 906: 'decided',
 907: 'now...',
 908: 'shows',
 909: 'bummed',
 910: 'lazy',
 911: 'man,',
 912: 'answer',
 913: 'power',
 914: 'awesome!',
 915: 'dude',
 916: 'eye',
 917: 'learn',
 918: 'o',
 919: '--',
 920: 'ahh',
 921: 'him.',
 922: 'morning,',
 923: 'that!',
 924: 'green',
 925: 'ran',
 926: 'feet',
 927: 'aint',
 928: 'hehe',
 929: 'lol,',
 930: 'tweeting',
 931: ':o',
 932: 'wit',
 933: 'hospital',
 934: 'rock',
 935: 'liked',
 936: 'small',
 937: 'white',
 938: 'though!',
 939: 'days.',
 940: 'rip',
 941: 'perfect',
 942: 'jus',
 943: 'songs',
 944: 'y',
 945: 'list',
 946: 'freaking',
 947: 'episode',
 948: 'tonight!',
 949: 'twitter.',
 950: 'pictures',
 951: 'today...',
 952: 'go.',
 953: 'download',
 954: 'living',
 955: 'david',
 956: 'each',
 957: 'disappointed',
 958: 'die',
 959: 'giving',
 960: 'played',
 961: 'camera',
 962: 'account',
 963: 'passed',
 964: 'front',
 965: 'better.',
 966: 'sorry,',
 967: 'upload',
 968: 'plan',
 969: 'home,',
 970: 'worked',
 971: 'know!',
 972: 'jonas',
 973: 'uk',
 974: 'team',
 975: 'updates',
 976: 'apple',
 977: 'starts',
 978: 'warm',
 979: 'terrible',
 980: 'different',
 981: 'moment',
 982: 'good,',
 983: 'again,',
 984: ":'(",
 985: '2nd',
 986: 'pool',
 987: 'message',
 988: 'worried',
 989: 'off.',
 990: 'hanging',
 991: 'wow,',
 992: 'earlier',
 993: 'date',
 994: 'sims',
 995: 'completely',
 996: 'behind',
 997: 'pissed',
 998: 'line',
 999: 'sign',
 1000: 'nobody',
 ...}

In [140]:
tk.word_counts

OrderedDict([('is', 158924),
             ('upset', 2054),
             ('that', 86115),
             ('he', 19563),
             ("can't", 34786),
             ('update', 2353),
             ('his', 10492),
             ('facebook', 1995),
             ('by', 16225),
             ('texting', 400),
             ('it...', 1129),
             ('and', 195634),
             ('might', 6063),
             ('cry', 2731),
             ('as', 24539),
             ('a', 242487),
             ('result', 312),
             ('school', 11370),
             ('today', 26053),
             ('also.', 166),
             ('blah!', 131),
             ('@kenichan', 13),
             ('i', 548319),
             ('dived', 2),
             ('many', 5776),
             ('times', 3439),
             ('for', 134588),
             ('the', 336920),
             ('ball.', 58),
             ('managed', 661),
             ('to', 389880),
             ('save', 1529),
             ('50%', 110),
             ('rest', 2908),
             ('go', 49064),
             ('out', 46859),
             ('of', 120733),
             ('bounds', 4),
             ('my', 226701),
             ('whole', 4229),
             ('body', 1706),
             ('feels', 3870),
             ('itchy', 311),
             ('like', 50782),
             ('its', 30202),
             ('on', 106109),
             ('fire', 720),
             ('@nationwideclass', 6),
             ('no,', 2303),
             ("it's", 43483),
             ('not', 81055),
             ('behaving', 39),
             ('at', 76329),
             ('all.', 1723),
             ("i'm", 89216),
             ('mad.', 170),
             ('why', 20302),
             ('am', 32876),
             ('here?', 307),
             ('because', 10047),
             ('see', 27046),
             ('you', 131363),
             ('all', 49940),
             ('over', 13849),
             ('there.', 1980),
             ('@kwesidei', 1),
             ('crew', 303),
             ('need', 26039),
             ('hug', 997),
             ('@loltrish', 1),
             ('hey', 6929),
             ('long', 10448),
             ('time', 28057),
             ('no', 52206),
             ('see!', 151),
             ('yes..', 58),
             ('rains', 310),
             ('bit', 6214),
             (',only', 1),
             ('lol', 22986),
             (',', 4344),
             ('fine', 1511),
             ('thanks', 12721),
             ("how's", 824),
             ('?', 5575),
             ('just', 81986),
             ('re-pierced', 2),
             ('ears', 483),
             ('@caregiving', 2),
             ("couldn't", 4095),
             ('bear', 440),
             ('watch', 9378),
             ('it.', 9711),
             ('thought', 7178),
             ('ua', 13),
             ('loss', 652),
             ('was', 72273),
             ('embarrassing', 107),
             ('.', 8994),
             ('@octolinz16', 1),
             ('it', 129527),
             ('counts,', 5),
             ('idk', 1600),
             ('did', 15618),
             ('either.', 715),
             ('never', 12951),
             ('talk', 5179),
             ('me', 89489),
             ('anymore', 3244),
             ('@smarrison', 1),
             ("would've", 396),
             ('been', 23542),
             ('first,', 184),
             ('but', 93934),
             ("didn't", 16291),
             ('have', 101662),
             ('gun.', 13),
             ('really', 34770),
             ('though,', 1178),
             ('zac', 133),
             ("snyder's", 1),
             ('doucheclown.', 1),
             ('@iamjazzyfizzle', 1),
             ('wish', 23288),
             ('got', 41001),
             ('with', 68501),
             ('you!!', 659),
             ('miss', 31918),
             ('@iamlilnicki', 1),
             ('how', 26054),
             ('premiere?!', 1),
             ("hollis'", 1),
             ('death', 1020),
             ('scene', 321),
             ('will', 31261),
             ('hurt', 3591),
             ('severely', 59),
             ('film', 834),
             ('wry', 9),
             ('directors', 19),
             ('cut', 2471),
             ('now?', 948),
             ('about', 32817),
             ('file', 354),
             ('taxes', 72),
             ('@lettya', 3),
             ('ahh', 1381),
             ('ive', 2485),
             ('always', 8739),
             ('wanted', 5847),
             ('rent', 304),
             ('love', 28697),
             ('soundtrack!!', 3),
             ('@fakerpattypattz', 1),
             ('oh', 22866),
             ('dear.', 279),
             ('were', 12133),
             ('drinking', 1544),
             ('forgotten', 343),
             ('table', 409),
             ('drinks?', 10),
             ('@alydesigns', 1),
             ('most', 4682),
             ('day', 39810),
             ('so', 103000),
             ('get', 55765),
             ('much', 20786),
             ('done', 7068),
             ('one', 29873),
             ('friend', 5206),
             ('called', 2724),
             ('me,', 3115),
             ('asked', 1140),
             ('meet', 2894),
             ('her', 19121),
             ('mid', 211),
             ('valley', 129),
             ('today...but', 38),
             ("i've", 13766),
             ('*sigh*', 1061),
             ('@angry_barista', 1),
             ('baked', 206),
             ('cake', 993),
             ('ated', 3),
             ('this', 61740),
             ('week', 9993),
             ('going', 41687),
             ('had', 33692),
             ('hoped', 187),
             ('blagh', 5),
             ('class', 3264),
             ('8', 2371),
             ('tomorrow', 14092),
             ('hate', 17675),
             ('when', 26984),
             ('call', 5049),
             ('wake', 3189),
             ('people', 11278),
             ('up', 51067),
             ('myself', 4791),
             ('sleep', 14606),
             ('after', 12265),
             ('watching', 12098),
             ('marley', 245),
             ('me.', 7802),
             ('im', 35103),
             ('sad', 21009),
             ('now', 44491),
             ('miss.lilly', 1),
             ('ooooh....', 2),
             ('leslie....', 1),
             ('ok', 5549),
             ("won't", 8627),
             ('do', 39808),
             ('again', 11968),
             ('leslie', 34),
             ('mad', 2600),
             ('meh...', 15),
             ('almost', 5124),
             ('lover', 139),
             ('exception...', 2),
             ('track', 656),
             ('gets', 2985),
             ('depressed', 910),
             ('every', 4271),
             ('time.', 3238),
             ('some1', 176),
             ('hacked', 238),
             ('account', 1316),
             ('aim', 377),
             ('make', 15936),
             ('new', 22748),
             ('@alielayus', 1),
             ('want', 32664),
             ('promote', 95),
             ('gear', 234),
             ('groove', 48),
             ('unfornately', 2),
             ('ride', 1673),
             ('there', 20307),
             ('may', 5281),
             ('b', 2926),
             ('in', 142578),
             ('anaheim', 30),
             ('though', 10176),
             ('sleeping', 2415),
             ('an', 23103),
             ('option', 350),
             ('realizing', 173),
             ('not.', 964),
             ('evaluations', 6),
             ('morning', 13191),
             ('work', 39022),
             ('afternoon!', 135),
             ('@julieebaby', 2),
             ('awe', 378),
             ('too!!!!', 58),
             ('1', 5472),
             ('here', 17594),
             ('@humpninja', 2),
             ('asian', 226),
             ('eyes', 2066),
             ('night', 17527),
             ('sick', 10819),
             ('spent', 1859),
             ('hour', 4600),
             ('sitting', 3596),
             ('shower', 1544),
             ('cause', 4562),
             ('too', 33332),
             ('stand', 906),
             ('held', 211),
             ('back', 35445),
             ('puke', 105),
             ('champ.', 7),
             ('bed', 9937),
             ('@cocomix04', 1),
             ('ill', 4142),
             ('tell', 5975),
             ('ya', 3884),
             ('story', 1231),
             ('later', 3618),
             ('good', 41370),
             ('be', 74184),
             ('workin', 568),
             ('three', 1925),
             ('more', 22650),
             ('hours...', 153),
             ('@missxu', 13),
             ('sorry!', 827),
             ('came', 3861),
             ('(gmt+1)', 3),
             ('http://is.gd/fnge', 1),
             ('@fleurylis', 2),
             ("don't", 37044),
             ('depressing.', 204),
             ('think', 26473),
             ('even', 14076),
             ('know', 27927),
             ('kids', 2902),
             ('suitcases.', 3),
             ('bed.', 2490),
             ('8-12.', 2),
             ('12-3.', 2),
             ('gym', 1585),
             ('3-5', 29),
             ('or', 18956),
             ('6.', 131),
             ('then', 18307),
             ('6-10.', 3),
             ('another', 9869),
             ("that's", 12657),
             ('gonna', 16059),
             ('fly', 939),
             ('by.', 98),
             ('girlfriend', 428),
             ('feel', 24006),
             ('getting', 16699),
             ('today...', 1328),
             ('study', 2655),
             ('tomorrows', 147),
             ('practical', 67),
             ('exam...', 62),
             ("he's", 5138),
             ('reason', 1814),
             ('teardrops', 17),
             ('guitar', 882),
             ('only', 20184),
             ('who', 9797),
             ('has', 24633),
             ('enough', 3971),
             ('break', 2414),
             ('heart', 2729),
             ('sad,', 873),
             ('sad.', 3228),
             ('feeling', 11641),
             ('wanna', 13014),
             ('still', 32180),
             ("can't!", 88),
             ('@jonathanrknight', 686),
             ('awww', 2696),
             ('soo', 3493),
             ('finally', 5682),
             ('comfortable!', 4),
             ('missed', 8853),
             ('falling', 1003),
             ('asleep.', 419),
             ('heard', 3131),
             ('tracy', 43),
             ("girl's", 75),
             ('being', 11854),
             ('found.', 76),
             ('breaks', 379),
             ('family.', 532),
             ('@viennah', 3),
             ('yay!', 1843),
             ('happy', 12815),
             ('your', 34894),
             ('job!', 307),
             ('also', 4979),
             ('means', 2358),
             ('less', 2059),
             ('you...', 591),
             ('checked', 827),
             ('user', 258),
             ('timeline', 71),
             ('blackberry,', 30),
             ('looks', 6677),
             ('twanking', 1),
             ('happening', 734),
             ('are', 46354),
             ('ppl', 1996),
             ('having', 10930),
             ('probs', 303),
             ('w/', 2644),
             ('bgs', 9),
             ('uids?', 1),
             ('man...was', 1),
             ('ironing', 180),
             ("@jeancjumbe's", 1),
             ('fave', 508),
             ('top', 1892),
             ('wear', 1545),
             ('meeting.', 168),
             ('burnt', 1115),
             ('strangely', 61),
             ('lilo', 11),
             ('samro', 1),
             ('breaking', 753),
             ('up.', 3535),
             ('@tea', 1),
             ('oh!', 362),
             ('sorry', 17289),
             ('before', 8172),
             ('retweeting.', 25),
             ('broadband', 134),
             ('plan', 1307),
             ("'a", 27),
             ('massive', 660),
             ('broken', 2203),
             ("promise'", 1),
             ('http://tinyurl.com/dcuc33', 1),
             ('via', 988),
             ('www.diigo.com/~tautao', 1),
             ('waiting', 6186),
             ('we', 31677),
             ('@localtweeps', 3),
             ('wow,', 1263),
             ('tons', 469),
             ('replies', 384),
             ('from', 36478),
             ('you,', 2810),
             ('unfollow', 217),
             ('can', 27807),
             ("friends'", 46),
             ('tweets,', 180),
             ("you're", 9981),
             ('scrolling', 37),
             ('feed', 587),
             ('lot.', 404),
             ('our', 9565),
             ('duck', 154),
             ('chicken', 1121),
             ('taking', 3873),
             ('wayyy', 128),
             ('hatch', 17),
             ('put', 5435),
             ('vacation', 1206),
             ('photos', 1037),
             ('online', 2290),
             ('few', 5703),
             ('yrs', 386),
             ('ago.', 824),
             ('pc', 967),
             ('crashed,', 23),
             ('forget', 1548),
             ('name', 2335),
             ('site.', 274),
             ('@andywana', 1),
             ('sure', 7385),
             ('what', 32012),
             ('they', 25147),
             ('are,', 146),
             ('pos!', 4),
             ('to,', 435),
             ('dont', 14047),
             ('trade', 198),
             ('away', 7014),
             ('company', 841),
             ('assets', 17),
             ('andy!', 16),
             ('@oanhlove', 6),
             ('happens...', 17),
             ('dallas', 377),
             ('show', 7619),
             ('gotta', 6226),
             ('say', 8762),
             ("you'd", 669),
             ('shows', 1403),
             ('would', 17352),
             ('use', 4879),
             ('music', 3629),
             ('game.', 630),
             ('mmm', 482),
             ('ugh....92', 1),
             ('degrees', 593),
             ('where', 9379),
             ('u', 28962),
             ('move', 2313),
             ('to?', 342),
             ('already', 8135),
             ('sd.', 25),
             ('??', 860),
             ('hmmm.', 98),
             ('random', 943),
             ('found', 5600),
             ('glad', 4766),
             ('hear', 6496),
             ('yer', 203),
             ('doing', 9501),
             ('well.', 2350),
             ('@batmanyng', 1),
             ('ps3,', 22),
             ('commission', 52),
             ('wutcha', 3),
             ('playing?', 24),
             ('copped', 18),
             ("'blood", 1),
             ("sand'?", 1),
             ('leaving', 3996),
             ('parking', 409),
             ('lot', 4877),
             ('work!', 1481),
             ('life', 7072),
             ('cool.', 969),
             ('sadly', 1569),
             ('gotten', 965),
             ('experience', 539),
             ('post', 2652),
             ('coitus', 1),
             ('cigarette', 72),
             ('before,', 196),
             ('will.', 232),
             ('such', 5874),
             ('nice', 10000),
             ('day.', 5261),
             ('bad', 19273),
             ('rain', 6596),
             ('comes', 2181),
             ('5am', 384),
             ('@starrbby', 6),
             ('around', 5050),
             ('lost', 8603),
             ('job', 4018),
             ('pay', 1849),
             ('phone', 8377),
             ('bill', 580),
             ('lmao', 1553),
             ('aw', 2073),
             ('shucks', 48),
             ('damm', 84),
             ('mo', 385),
             ('jobs,', 20),
             ('money.', 385),
             ('hell', 2897),
             ('min', 773),
             ('wage', 28),
             ('4', 10073),
             ("f'n", 47),
             ('clams', 5),
             ('hour?', 39),
             ('@katortiz', 2),
             ('forever...', 42),
             ('soon!', 1416),
             ('@lt_algonquin', 6),
             ('agreed,', 43),
             ('saw', 5986),
             ('failwhale', 5),
             ('allllll', 64),
             ('today.', 8118),
             ('@jdarter', 1),
             ('haha...', 127),
             ('dude', 1393),
             ('look', 7272),
             ('em', 945),
             ('unless', 795),
             ('someone', 7880),
             ('says', 3842),
             ('added', 583),
             ('you.', 4620),
             ('terrible', 1288),
             ('that.', 2923),
             ('pop', 586),
             ('up!', 1862),
             ('@ninjen', 11),
             ('right...', 127),
             ('start', 6348),
             ('working', 10718),
             ('nikster...', 1),
             ('jared', 98),
             ('least!', 39),
             ('diss', 33),
             ('bands!', 13),
             ('trace', 82),
             ('clearly', 329),
             ('ugly!', 21),
             ('attire', 11),
             ('was:', 9),
             ('puma', 16),
             ('singlet,', 1),
             ('adidas', 18),
             ('shorts.......and', 1),
             ('black', 1618),
             ('business', 947),
             ('socks', 211),
             ('leather', 116),
             ('shoes', 977),
             ('lucky', 2117),
             ('run', 2892),
             ('into', 7691),
             ('any', 10668),
             ('cute', 2295),
             ('girls.', 208),
             ('location?!', 1),
             ('http://twitpic.com/2y2es', 1),
             ('picnic', 244),
             ('smells', 477),
             ('citrus.', 3),
             ('@ashleyac', 2),
             ('donkey', 55),
             ('sensitive', 98),
             ('comments.', 42),
             ('nevertheless,', 12),
             ("he'd", 221),
             ('(and', 646),
             ("me'd)", 1),
             ('mug', 117),
             ('asap.', 107),
             ('charger', 410),
             ('awol.', 4),
             ('csi', 110),
             ('tonight.', 3083),
             ('fml', 904),
             ('arms', 461),
             ('sore', 2967),
             ('tennis', 419),
             ('wonders', 336),
             ('unhappy', 247),
             ('split', 274),
             ('seccond', 1),
             ('soon...', 293),
             ('saying', 1958),
             ('bye', 2206),
             ('night.', 3652),
             ('@statravelau', 1),
             ('ur', 7238),
             ('newsletter,', 5),
             ('those', 5963),
             ('fares', 12),
             ('unbelievable,', 9),
             ('shame', 1848),
             ('booked', 376),
             ('paid', 872),
             ('mine', 3785),
             ("missin'", 83),
             ('boo', 2575),
             ('@markhardy1974', 2),
             ('#itm', 2),
             ('damn...', 162),
             ('chalk!', 2),
             ('chalkboard', 6),
             ('useless', 250),
             ('blast', 418),
             ('getty', 11),
             ('villa,', 3),
             ('hates', 1913),
             ("she's", 3817),
             ('throat', 2265),
             ('worse', 1661),
             ('@msdrama', 3),
             ('meeting', 1779),
             ('sup', 88),
             ('mama', 468),
             ('tummy', 1932),
             ('hurts.', 945),
             ('wonder', 1786),
             ('if', 26195),
             ('hypnosis', 9),
             ('anything', 4776),
             ('it?', 1931),
             ('so,', 1184),
             ('working,', 270),
             ('it,', 3454),
             ('stop', 5209),
             ('smoking!!!', 1),
             ('fat', 1013),
             ('ones?!', 4),
             ('@januarycrimson', 5),
             ('sorry,', 1310),
             ('babe!!', 29),
             ('fam', 581),
             ('annoys', 75),
             ('too.', 4547),
             ('thankfully,', 30),
             ("they're", 3297),
             ('asleep', 2520),
             ('right', 15157),
             ('now.', 7922),
             ('muahaha.', 5),
             ('*evil', 10),

In [141]:
tweet_sequences = tk.texts_to_sequences(data_train_feture)

In [142]:
tweet_sequences

[[7,
  659,
  19,
  98,
  49,
  596,
  159,
  676,
  112,
  2523,
  1086,
  6,
  264,
  534,
  81,
  4,
  3046,
  147,
  74,
  4966,
  5982],
 [33414,
  1,
  142205,
  281,
  455,
  9,
  3,
  11150,
  1670,
  2,
  852,
  6839,
  3,
  512,
  32,
  33,
  12,
  82947],
 [5, 372, 771, 405, 3056, 6, 30, 61, 13, 1560],
 [60496,
  605,
  36,
  21,
  14928,
  22,
  767,
  18,
  4875,
  95,
  53,
  1,
  3085,
  166,
  1,
  49,
  68,
  10,
  31,
  126,
  681],
 [236582, 21, 3, 372, 3123],
 [75, 4, 1194],
 [236583,
  231,
  160,
  65,
  28,
  5366,
  11151,
  3062,
  4,
  257,
  236584,
  4,
  257,
  86,
  364,
  18,
  862,
  136,
  364,
  1403,
  10,
  292],
 [1, 20, 142206, 5, 2146],
 [142207,
  1,
  383,
  2325,
  2,
  178,
  173,
  6,
  1,
  222,
  3,
  33415,
  1682,
  24,
  6979,
  184,
  184,
  184,
  184,
  184],
 [236585, 11, 11, 69618, 822, 95, 1, 115, 1566, 10, 133, 320, 2, 17, 472],
 [236586,
  1,
  2543,
  83,
  3,
  4610,
  16,
  1,
  111,
  15,
  4,
  33416,
  21,
  50,
  1059,
  5916,
  236587,
  20,
  4,
  236588],
 [236589,
  1,
  84,
  1,
  39,
  2,
  178,
  11,
  25,
  1675,
  1,
  58,
  10,
  6,
  236590,
  73,
  24,
  3,
  236591],
 [236592,
  1177,
  2985,
  60,
  434,
  17,
  11008,
  2,
  178,
  13,
  1388,
  44171,
  7,
  25242,
  578,
  21,
  33,
  1243],
 [54, 2, 2771, 9474],
 [103962, 920, 575, 189, 278, 2, 68, 3113, 64, 3, 103963],
 [236593, 87, 3339, 140, 10, 843, 33, 12, 3, 2837, 2478, 40753],
 [236594, 1, 24, 33, 345, 12, 3, 40, 14, 111, 27, 93, 226],
 [62,
  12,
  5,
  316,
  538,
  484,
  6,
  1083,
  2,
  518,
  25,
  100,
  22,
  4139,
  6047,
  15228,
  127,
  28,
  65,
  1136],
 [236595, 1, 4226, 10, 4, 1198, 16, 1, 103964, 11],
 [26, 168, 7, 21, 37, 81, 1, 51, 4541],
 [69619, 470, 22, 589, 123],
 [1, 103, 69, 1, 15, 2, 326, 6, 479, 148, 29],
 [20, 37, 2, 534, 334, 2, 122, 139, 141, 3708, 6, 207],
 [47, 92, 35, 236596],
 [142208,
  86,
  19,
  236597,
  6,
  294,
  1,
  190,
  41,
  11,
  142,
  14,
  16504,
  190,
  27,
  555,
  142],
 [30029, 323, 5723, 7, 3, 142209, 26, 1679, 498, 17, 1279, 369, 473],
 [4759, 3786, 5, 962, 13, 2650, 35, 1, 15, 2, 114, 4, 88, 62],
 [236598,
  1,
  55,
  2,
  32,
  2,
  7675,
  3839,
  6,
  12828,
  16,
  142210,
  28,
  791,
  94,
  1,
  310,
  510,
  37,
  2,
  3,
  62,
  8,
  18084,
  8,
  310,
  164],
 [222,
  584,
  8,
  24,
  85,
  2796,
  123,
  16,
  4810,
  19,
  11,
  35,
  7,
  1230,
  60497,
  8,
  3,
  129,
  6,
  42,
  8,
  3,
  5862],
 [142211, 2643, 1, 64, 10, 11152, 297, 53, 104, 1, 58, 10],
 [142212, 1, 534, 5, 3939, 654, 2, 122, 22, 105],
 [294,
  18,
  152,
  6,
  730,
  85,
  348,
  433,
  8,
  3,
  844,
  350,
  1,
  24,
  52,
  152,
  2,
  1283,
  6,
  4140,
  46,
  3,
  7083,
  30,
  4,
  53721,
  170,
  35],
 [236599,
  379,
  269,
  402,
  3,
  1015,
  432,
  21,
  4,
  38,
  40,
  6,
  379,
  23,
  1880,
  9,
  30,
  704,
  89,
  5309],
 [33417, 1395, 170, 65, 406, 104, 103965, 236600],
 [142213,
  1,
  44,
  1566,
  61,
  4259,
  1,
  44,
  71,
  1,
  124,
  55,
  2,
  66,
  54,
  3,
  515,
  8,
  103966],
 [573,
  470,
  142214,
  42,
  142215,
  825,
  18531,
  101,
  5983,
  102,
  470,
  103967,
  171,
  40,
  137,
  113,
  1254,
  7474,
  1,
  58,
  5,
  2386],
 [50, 44, 82, 30, 110, 29, 951, 16, 39, 2, 545, 2, 9, 5469, 10043, 10616],
 [322,
  3,
  744,
  9,
  3,
  27345,
  13,
  5,
  1316,
  3,
  96,
  62,
  172,
  80,
  395,
  12,
  17,
  2,
  585,
  5,
  535],
 [1322,
  1322,
  475,
  1,
  44,
  66,
  95,
  16,
  1,
  103,
  26,
  145,
  1,
  132,
  122,
  6,
  1,
  56,
  8132],
 [1620,
  541,
  1,
  450,
  84,
  1,
  24,
  94,
  2,
  68,
  10,
  287,
  82948,
  47,
  92,
  19,
  1,
  185,
  11],
 [1187,
  2426,
  20,
  482,
  54,
  19,
  13916,
  9224,
  771,
  144,
  9136,
  73,
  92,
  5,
  535,
  2635,
  9,
  19,
  1977],
 [103968,
  738,
  18,
  135,
  9,
  10,
  25,
  48,
  3086,
  16,
  19,
  327,
  594,
  656,
  65,
  9,
  17,
  6,
  1818],
 [20,
  1396,
  5,
  3554,
  9596,
  13,
  5,
  18085,
  11,
  242,
  30,
  3,
  236601,
  7,
  56,
  1537,
  34,
  675,
  56,
  151,
  3124,
  549,
  44172,
  6,
  236602],
 [87, 236603, 4686, 236604, 2070, 715, 2, 842, 2, 4, 4917, 1097, 11],
 [7, 10749, 92, 54, 37906, 6, 236605, 1506, 444],
 [236606, 2720, 18, 14, 107, 1, 111, 71, 54, 19, 196, 20680],
 [5896,
  968,
  19528,
  1672,
  629,
  236607,
  236608,
  1201,
  236609,
  56,
  258,
  9,
  5896,
  59,
  34],
 [103969,
  991,
  2203,
  12,
  2609,
  45,
  525,
  310,
  15,
  2,
  4059,
  14,
  1,
  67,
  68,
  5,
  13238,
  4687,
  169,
  15537,
  3,
  1826,
  4,
  2498],
 [174, 5273, 6, 1093, 34, 404, 6085, 52, 160, 2, 27346],
 [301,
  1033,
  1157,
  609,
  4,
  285,
  2594,
  1404,
  1224,
  21974,
  6,
  35,
  1,
  839,
  3,
  598,
  12,
  3,
  3384],
 [1, 75, 4, 1194],
 [236610,
  21,
  217,
  57,
  77,
  5497,
  96,
  19,
  77,
  34,
  82949,
  81,
  93,
  81,
  1,
  55,
  2357,
  1,
  125,
  71,
  67,
  4355,
  228,
  1380,
  27347,
  107,
  28596],
 [60498, 1, 103, 69, 19, 27348],
 [1,
  15,
  4,
  92,
  145,
  19,
  2651,
  7,
  21,
  37,
  2,
  210,
  29,
  1,
  255,
  188,
  1059,
  1656,
  71,
  89,
  908,
  106,
  330,
  431,
  45,
  3,
  1733,
  2152],
 [236611, 1813, 123],
 [177,
  115,
  63,
  604,
  2846,
  1,
  222,
  63,
  140,
  198,
  8,
  20681,
  1342,
  7475,
  1249,
  63,
  291,
  207,
  340,
  2,
  248,
  4266,
  175,
  597],
 [236612,
  1,
  58,
  5,
  22730,
  36,
  33,
  12,
  12079,
  103970,
  21272,
  15,
  10,
  26230,
  236613,
  13,
  3,
  236614],
 [20, 392, 3, 2479, 331, 12, 875],
 [3, 225, 7, 1223, 16, 21, 9, 207],
 [832,
  1059,
  127,
  133,
  1226,
  2,
  1959,
  3,
  546,
  236615,
  9475,
  4385,
  6,
  35,
  1,
  133,
  3861],
 [1, 51, 277, 4, 167, 312, 52, 99, 3, 244, 638, 8, 123, 22, 2610],
 [60499,
  52,
  99,
  1,
  190,
  23,
  325,
  1,
  191,
  5,
  390,
  6,
  49,
  124,
  735,
  5,
  194,
  1849,
  836,
  653,
  12829],
 [8482, 46, 2, 147, 123],
 [2601,
  24326,
  28,
  2602,
  73,
  8,
  3,
  517,
  7,
  1481,
  18995,
  104,
  165,
  13045,
  69620,
  85,
  14929],
 [142216, 21, 14130, 68, 10, 903],
 [60500, 13917, 1, 267, 3, 69621, 10358, 40, 199],
 [236616,
  2720,
  6118,
  915,
  1,
  125,
  50,
  218,
  22,
  1245,
  1448,
  204,
  407,
  231,
  1,
  1840,
  346,
  107,
  18,
  14,
  979,
  22,
  511,
  1,
  75,
  4,
  1832,
  725],
 [37907,
  18,
  217,
  169,
  6119,
  1,
  75,
  2,
  251,
  155,
  33,
  25,
  10,
  6,
  3,
  236617,
  101,
  7476,
  22,
  14930],
 [1, 50, 103, 73, 148, 16872, 5, 33418, 8640, 7, 2926, 21, 23483],
 [825,
  37908,
  74,
  44173,
  28597,
  236618,
  26231,
  236619,
  814,
  1244,
  4141,
  6,
  6530,
  1214,
  647,
  115,
  21,
  519,
  209,
  156,
  608,
  4194],
 [95, 190, 10, 210, 5, 236620, 236621],
 [28, 3719, 5, 194, 2173, 30, 103971],
 [142217,
  5,
  11597,
  7,
  7477,
  54,
  277,
  14131,
  35470,
  4002,
  1698,
  236622,
  23,
  340,
  2,
  68,
  48,
  6491,
  6980,
  2471,
  7,
  56,
  82950],
 [28, 88, 6840, 487, 1288],
 [1, 71, 5, 2237, 34, 501, 45, 2427],
 [2891,
  95,
  204,
  19,
  63,
  30,
  14,
  93,
  67,
  114,
  10,
  14,
  3679,
  8,
  4,
  3385,
  236623,
  184,
  1279,
  184],
 [122, 3199, 1, 20, 103, 692, 627, 6, 68, 10, 123, 9, 3, 426],
 [236624,
  20,
  39,
  220,
  69622,
  270,
  35471,
  50,
  34,
  44174,
  736,
  1,
  198,
  2658,
  6,
  1326,
  9,
  413],
 [8558, 3, 562],
 [142218, 17, 52, 142219],
 [5060, 1, 44, 15, 156, 142220, 5, 60501, 7, 3641],
 [51,
  4,
  2433,
  22,
  3,
  37909,
  103972,
  16,
  710,
  19,
  410,
  51,
  4,
  501,
  618,
  31,
  312,
  36,
  20,
  110,
  797,
  52],
 [103973, 231, 185, 402, 22, 3, 754, 8133, 2210],
 [5,
  697,
  1246,
  1,
  753,
  72,
  3,
  44175,
  80,
  338,
  2,
  41,
  25,
  698,
  72,
  1054,
  36,
  3424,
  1,
  27,
  454,
  315,
  236625],
 [95, 7, 11, 189, 3, 1180, 82951],
 [69623,
  966,
  18532,
  5,
  1846,
  9225,
  17,
  351,
  18086,
  466,
  567,
  118,
  202,
  69624,
  40754,
  69625],
 [53722,
  1,
  134,
  15,
  1326,
  89,
  2482,
  69,
  59,
  2434,
  3810,
  8,
  5,
  21273,
  1904,
  470,
  8,
  26232],
 [1420, 5, 21274, 44, 66, 57, 79, 6163],
 [219, 11748, 3531, 142221],
 [1148,
  9,
  17,
  2847,
  3,
  2702,
  7,
  14656,
  2,
  251,
  53723,
  22,
  236626,
  2193,
  761,
  418,
  2153,
  57,
  4,
  12080,
  6,
  1,
  56,
  15,
  4,
  419],
 [236627,
  1450,
  364,
  41,
  63,
  50,
  478,
  144,
  25,
  161,
  292,
  72,
  3,
  1256,
  34,
  52,
  142222,
  63,
  134,
  71,
  249,
  89,
  364,
  154,
  204,
  142223],
 [236628, 7, 4, 152, 157, 1301, 236629],
 [14,
  236630,
  32,
  30030,
  381,
  101,
  22731,
  832,
  240,
  61,
  3025,
  1,
  6260,
  510,
  362,
  79,
  41,
  93,
  16,
  1253,
  21275],
 [1139, 1, 303, 833, 62, 12, 5, 21975, 103974, 52, 99, 11, 384, 3, 62, 9, 435],
 [236631, 10, 44, 339, 484, 551, 6, 1, 42, 9, 365],
 [4,
  99,
  861,
  9,
  3,
  708,
  236632,
  21976,
  6,
  48420,
  11910,
  3,
  861,
  33,
  25,
  142224,
  24,
  520],
 [771,
  12,
  227,
  6692,
  69626,
  374,
  103975,
  3147,
  15,
  291,
  3,
  9795,
  12,
  4,
  227,
  6692,
  2703,
  374,
  274,
  236633],
 [236634,
  1,
  97,
  77,
  60,
  7792,
  3,
  13046,
  7793,
  398,
  24,
  277,
  4,
  2014,
  39,
  3,
  740,
  6193,
  103976,
  455,
  8,
  79,
  21276],
 [996, 13, 5, 1422, 9, 42],
 [141, 40755],
 [236635, 532, 5, 3475, 40756, 8236, 46, 26, 65, 61, 1306],
 [236636,
  1685,
  1,
  3861,
  290,
  34,
  31,
  4329,
  12,
  15229,
  54,
  26,
  621,
  609,
  54,
  142225,
  16,
  28,
  69627],
 [4427,
  60,
  23,
  340,
  69,
  1333,
  7,
  226,
  1382,
  22,
  100,
  88,
  1865,
  116,
  1091,
  1209,
  236637],
 [106,
  714,
  3,
  182,
  381,
  493,
  99,
  1731,
  179,
  3,
  1529,
  381,
  493,
  3302,
  751,
  37910,
  318,
  31,
  126,
  1906],
 [142226, 36, 17659],
 [236638,
  1,
  971,
  1,
  482,
  11,
  26,
  880,
  6,
  7343,
  3,
  239,
  1240,
  17255,
  7,
  14,
  996,
  3,
  455],
 [1216, 8, 170, 25, 28, 22732],
 [18, 370, 8134, 77, 1128, 90, 22733, 13, 254, 40757],
 [142227, 107, 269, 138, 40758, 103977, 45, 17, 6, 19, 1, 50, 53, 800],
 [142228,
  11,
  111,
  114,
  156,
  1972,
  2,
  484,
  3,
  6981,
  1240,
  1,
  4562,
  2,
  306,
  19,
  19,
  7,
  303,
  57,
  4142],
 [236639, 97, 48, 1202],
 [82952,
  2362,
  3,
  5592,
  7,
  13675,
  6,
  22734,
  22,
  3,
  239,
  473,
  44,
  55,
  10,
  2,
  315,
  430,
  1,
  30,
  57,
  63,
  1499,
  93,
  64],
 [48421, 221, 653, 16, 1, 66, 1, 18996, 1283, 4, 805],
 [837, 128, 506, 61, 69628],
 [990, 8, 236640, 132, 16172, 3011, 749],
 [236641,
  15538,
  1,
  58,
  402,
  31,
  3026,
  47,
  392,
  2,
  17660,
  123,
  82953,
  1,
  13464,
  363,
  1,
  132,
  32,
  2,
  3,
  571,
  1270,
  63,
  18533],
 [7, 997, 90, 19, 385, 28, 236642, 9, 4, 1075, 8008],
 [1420, 5, 2765, 260, 44, 66, 57, 79, 1499],
 [1,
  66,
  5,
  225,
  80,
  83,
  12643,
  4855,
  153,
  69,
  1,
  20,
  222,
  8,
  5,
  298,
  19,
  70,
  8885,
  355,
  520],
 [1, 53, 8, 2014, 5, 46, 6, 9137, 2271, 21, 2, 1625, 831, 7, 197, 12, 1792],
 [308,
  105,
  40759,
  1748,
  12,
  13239,
  1616,
  18,
  69629,
  25,
  3,
  236643,
  102,
  46,
  2,
  103978,
  1,
  103,
  110,
  3366],
 [82954, 6120, 6120, 6120, 18, 21, 4, 245, 786, 13, 18534, 10359],
 [22735,
  4563,
  1,
  49,
  68,
  35472,
  299,
  23,
  236644,
  42,
  69630,
  49,
  163,
  7603,
  1,
  27,
  4,
  142229,
  203,
  497,
  79,
  1787,
  2702,
  4900,
  98,
  458,
  413],
 [26,
  168,
  20,
  422,
  2,
  27,
  724,
  6,
  724,
  8,
  5565,
  12,
  73,
  93,
  1,
  75,
  2,
  5274,
  6,
  73,
  93,
  18,
  303,
  37,
  2,
  27,
  226],
 [18, 14, 305],
 [82955, 11153, 4371, 7344, 113, 150, 4, 645, 9, 3, 1628, 123],
 [236645,
  162,
  61,
  14,
  53724,
  8,
  3,
  16873,
  6,
  28,
  16,
  10,
  134,
  56,
  32,
  2,
  3,
  1373,
  77,
  41,
  70,
  4330,
  352],
 [548, 3, 697, 60502, 32, 228, 276],
 [236646,
  605,
  28,
  10263,
  77,
  488,
  17,
  329,
  23,
  155,
  1008,
  6,
  102,
  1,
  538,
  3,
  10750,
  2,
  339,
  29,
  6,
  77,
  280,
  11,
  24,
  1089],
 [323, 3622],
 [18,
  227,
  10,
  23484,
  16,
  81,
  160,
  81,
  48,
  2491,
  18,
  21977,
  236647,
  18,
  192,
  5,
  64,
  1623,
  275,
  2,
  122,
  485,
  10,
  51,
  4,
  69631],
 [236648],
 [1, 58, 8396, 7478],
 [82956,
  223,
  10,
  9,
  1532,
  148,
  807,
  16,
  35,
  18,
  92,
  19,
  3,
  1847,
  987,
  1,
  39,
  384,
  303,
  45,
  20682],
 [103979,
  3461,
  185,
  33,
  61,
  7290,
  699,
  8969,
  260,
  5659,
  17256,
  542,
  284,
  4,
  5216],
 [1620, 1, 216, 137, 4, 28, 1640],
 [832, 7, 37, 2, 573],
 [236649, 736, 2, 248, 26, 35473],
 [142230, 1508, 18, 3956, 8, 3, 2484],
 [24,
  48422,
  2,
  569,
  2681,
  5,
  236650,
  8800,
  53725,
  1085,
  16,
  19,
  60,
  361,
  21,
  3027,
  6,
  96,
  868,
  2241,
  34,
  205],
 [3441, 325, 52, 93, 951, 35, 5, 298, 304],
 [82957,
  1,
  56,
  256,
  337,
  3,
  236651,
  3200,
  23485,
  2969,
  48423,
  197,
  17,
  534,
  22,
  3,
  2578,
  1450,
  270,
  34,
  1040,
  5141],
 [5, 4657, 142231, 19529],
 [5,
  335,
  264,
  15,
  8397,
  2346,
  190,
  154,
  33,
  338,
  4477,
  30,
  4,
  168,
  18,
  14,
  14931],
 [37, 2, 506, 548, 123, 7, 4, 149, 312],
 [40760,
  2766,
  84,
  77,
  7736,
  10751,
  10360,
  80,
  1105,
  164,
  6,
  732,
  7,
  85,
  348,
  432,
  77,
  236,
  867,
  3,
  515,
  29,
  52],
 [236652, 19, 7, 1221],
 [1, 44, 17257, 1, 50, 44],
 [5079, 20, 272, 175, 11, 9, 17, 26, 17661],
 [954, 21, 2717, 217, 272, 93, 864],
 [142232,
  21,
  16173,
  5863,
  1,
  84,
  3826,
  421,
  24,
  16173,
  7252,
  1,
  613,
  4,
  213,
  12,
  5080,
  11598,
  6,
  4,
  245,
  610,
  4011,
  33419],
 [295, 42, 7, 262],
 [110, 152, 65, 9, 70, 273, 4688, 8641, 6, 102, 16174],
 [110, 9476, 103980, 89, 526],
 [28, 236653, 796, 398, 37, 2, 1248],
 [87,
  43,
  20,
  39,
  31,
  5,
  40761,
  1032,
  2129,
  43,
  3642,
  111,
  27,
  3,
  8725,
  11009,
  28,
  164,
  1041,
  77,
  280,
  77,
  750,
  11,
  43,
  87,
  108],
 [1587,
  18535,
  2870,
  2,
  542,
  11,
  31,
  45,
  3,
  27,
  952,
  24,
  145,
  234,
  38,
  54,
  19,
  790,
  31,
  3,
  131,
  29,
  236654,
  9796,
  191,
  52],
 [7, 496, 236655],
 [1, 82, 99, 9, 175, 11],
 [5593,
  7,
  11,
  20,
  484,
  101,
  116,
  710,
  69632,
  1,
  387,
  2986,
  410,
  386,
  387,
  2,
  921],
 [82958, 342, 5081, 80, 60503, 96, 8, 9797, 6, 1779, 14, 391],
 [18,
  366,
  600,
  8,
  3,
  1132,
  12,
  3,
  105,
  9,
  3,
  726,
  40,
  8,
  4,
  6048,
  6,
  1,
  801,
  979,
  1141],
 [136, 9, 21978, 5, 4083],
 [37, 2, 147, 3199, 49, 154, 338, 2, 82959, 1699, 36, 14, 262],
 [69633, 1, 24, 1306, 86],
 [60504,
  1,
  51,
  13,
  5,
  878,
  9,
  1063,
  30031,
  233,
  11,
  39,
  1700,
  92,
  40,
  8,
  1142],
 [550, 2387, 74, 474, 28, 103981, 236656],
 [1169, 22, 2304],
 [35474,
  5,
  13676,
  1819,
  829,
  459,
  16505,
  3957,
  6,
  356,
  12,
  10,
  663,
  380,
  3,
  486,
  19530,
  7676],
 [236657, 493, 17, 3, 1368, 857, 1, 15, 185, 33, 13, 4372, 21, 135, 54, 923],
 [1, 44, 68, 3, 245, 1327, 25, 26, 1087],
 [142233, 18, 14, 107, 169, 151, 2, 32, 373, 1183, 427, 236658],
 [236659, 391, 52, 33, 12, 3, 131, 9, 82960, 156, 246, 20683],
 [18,
  21,
  56,
  29,
  1,
  12644,
  95,
  41,
  1,
  236,
  18087,
  82961,
  18087,
  82961,
  31602,
  14,
  535,
  69634],
 [74, 1, 845, 1, 53, 52, 38, 22, 3633, 4856, 124, 1, 49, 154, 11],
 [1006, 22, 4, 238, 236660, 27349, 3878, 34, 14, 236661, 4, 381],
 [236662,
  1994,
  47,
  659,
  19,
  1,
  1101,
  104,
  2,
  178,
  3,
  261,
  1042,
  1,
  24,
  8,
  4,
  1894,
  9,
  181,
  206,
  13,
  4,
  588,
  47,
  547,
  40762],
 [414, 33, 5, 6491, 236663],
 [10361, 1068, 22, 477],
 [2326,
  40763,
  88,
  1070,
  1476,
  236664,
  43,
  69,
  3,
  517,
  115,
  26,
  119,
  2441,
  18,
  14,
  996,
  3,
  455,
  349,
  176],
 [20,
  259,
  29,
  85,
  198,
  15,
  2884,
  70,
  142234,
  127,
  2,
  32,
  241,
  22,
  4122,
  74,
  81,
  1,
  15,
  2,
  2353,
  22,
  5984,
  3292],
 [7, 141, 3, 2729, 184, 184, 27350, 61, 314, 17, 92],
 [14,
  281,
  236665,
  279,
  14,
  14,
  10044,
  910,
  40,
  142,
  310,
  15,
  2,
  154,
  4,
  12455],
 [142235, 1, 58, 5, 2030, 379, 23, 8, 1533, 13, 3, 9291],
 [10617,
  64,
  3,
  14132,
  1,
  269,
  148,
  104,
  8,
  3,
  1451,
  18,
  142236,
  1035,
  6,
  77,
  103982,
  22,
  207,
  1035,
  34,
  442,
  148],
 [236666, 81, 1, 25243, 1, 56, 39, 62, 40, 6583, 6, 35, 756, 119],
 [1,
  15230,
  5,
  236667,
  1844,
  3156,
  3532,
  1,
  49,
  414,
  33,
  3,
  88,
  69635,
  236668,
  5,
  8483,
  2772,
  7,
  264,
  23,
  9798,
  1016],
 [236669, 87, 28],
 [7677, 7, 21, 4, 38, 3132],
 [33420,
  57,
  54,
  22736,
  1018,
  13,
  236670,
  6,
  582,
  1711,
  143,
  652,
  27351,
  6335,
  33421,
  7604,
  7,
  4,
  550,
  8237],
 [1620,
  1,
  103,
  3,
  4012,
  236671,
  10,
  6,
  3,
  263,
  34,
  236672,
  1148,
  9,
  5,
  236673,
  21,
  108],
 [111, 27, 411, 226, 74, 1629, 18, 14, 1848],
 [236674, 2, 32, 33],
 [7, 21, 37, 2, 122, 7605],
 [52, 988, 6, 192, 2, 546, 187],
 [383, 27, 411, 226, 74, 1629, 18, 14, 1848],
 [390, 1397, 8, 8726, 449, 84, 17, 1889, 39, 54, 181, 206, 122],
 [142237, 48, 210, 7, 27352, 131, 797, 179, 69636, 36, 236675, 236676],
 [48424,
  1,
  50,
  44,
  71,
  148,
  2664,
  2,
  23,
  19,
  1384,
  16,
  1,
  71,
  98,
  4942,
  21,
  2,
  3099,
  5,
  10877,
  252,
  98,
  264,
  23,
  595,
  112,
  35],
 [103983,
  169,
  37,
  2,
  811,
  484,
  16,
  127,
  21,
  412,
  142238,
  127,
  83,
  258,
  293,
  1,
  67,
  41,
  11,
  8,
  62,
  4830,
  168,
  23486],
 [142239, 1, 71, 220, 11911, 13918, 11749, 1151, 2544],
 [1, 103, 2, 68, 3, 48420, 14, 92],
 [5, 657, 6, 771, 34, 11008, 24327, 26, 27353, 9916, 1240, 51, 3692, 2, 3879],
 [236677, 18, 6633, 2, 339, 3392, 240, 63, 111, 86, 32, 60505],
 [142240],
 [82957, 1, 71, 1, 55, 2, 337, 70, 1260, 16, 3, 1718, 193, 15, 138],
 [5, 892, 24, 12830, 14, 281, 455, 74, 37, 33, 9, 3201, 25, 3, 20067, 1516],
 [540,
  12,
  31603,
  9,
  3,
  826,
  19,
  908,
  29,
  22,
  3,
  358,
  12,
  3452,
  463,
  118,
  202,
  837],
 [103984,
  16,
  26,
  7,
  2133,
  2133,
  7,
  3213,
  423,
  565,
  2,
  27,
  2373,
  373,
  4798,
  837],
 [8398,
  103985,
  10,
  218,
  14,
  92,
  142241,
  19,
  1072,
  13047,
  12,
  142242,
  142243,
  142244,
  1,
  30,
  3,
  218,
  12,
  3,
  88,
  12456,
  332],
 [92, 19, 3, 82962, 12, 5, 1915, 20, 611, 90],
 [18,
  113,
  27,
  29,
  308,
  123,
  6,
  36,
  236678,
  572,
  1,
  113,
  27,
  12081,
  112,
  5,
  31604,
  103986,
  20,
  92],
 [18,
  6015,
  5,
  35475,
  588,
  2,
  18536,
  72,
  1,
  49,
  154,
  204,
  2,
  2017,
  25,
  268,
  18,
  33,
  1298,
  1,
  310,
  23,
  12645],
 [80, 35, 1226, 1339, 2, 337, 159, 4687, 16, 128, 27, 138, 2, 114, 85, 3940],
 [236679, 103987, 1, 1027, 1939, 5, 717, 144, 8, 1281, 31, 3, 65, 1414, 1414],
 [1410, 1, 97, 1, 67, 114, 11, 2, 3, 21277, 1373, 16, 61, 21, 195, 38, 9, 17],
 [8484,
  236680,
  148,
  5009,
  162,
  1,
  1027,
  1268,
  11,
  31,
  8886,
  1,
  125,
  71,
  270,
  950,
  265,
  197,
  11,
  8,
  3,
  4284,
  2004,
  162],
 [142245, 15539, 1, 360, 378, 2, 8135, 1157],
 [7345,
  2248,
  38,
  448,
  142246,
  200,
  44,
  42,
  52,
  262,
  16,
  1,
  97,
  10,
  15,
  158,
  48,
  88,
  1070,
  7,
  113,
  23,
  1635,
  784],
 [236681, 35, 48, 392, 17, 779, 103988, 33422],
 [1,
  58,
  10,
  949,
  5,
  194,
  8801,
  35,
  18,
  671,
  4,
  307,
  4657,
  1436,
  12646,
  1,
  58,
  5,
  7737,
  1436],
 [3191, 439, 5, 254, 931, 21, 9056, 14, 705],
 [236682,
  251,
  25,
  14932,
  60506,
  102,
  4,
  5753,
  8,
  1978,
  35476,
  60507,
  19,
  217,
  264,
  1430,
  109,
  4542,
  9,
  232,
  236683],
 [57, 8399, 6, 6736, 8, 3, 544, 26, 168],
 [342, 342, 56, 183, 2, 154, 4, 634, 19, 60, 967, 236684],
 [95,
  87,
  95,
  24,
  3,
  615,
  4689,
  354,
  2026,
  2441,
  1,
  24,
  14,
  195,
  371,
  2,
  2219,
  40],
 [1, 56, 49, 154, 5, 14657],
 [236685, 1, 66, 1549, 1, 1173, 57, 7, 37, 13, 25, 949],

In [143]:
pd.DataFrame(tweet_sequences).shape

(1048572, 57)

In [144]:
pd.DataFrame(tweet_sequences).head()

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,7,659.0,19.0,98.0,49.0,596.0,159.0,676.0,112.0,2523.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33414,1.0,142205.0,281.0,455.0,9.0,3.0,11150.0,1670.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,372.0,771.0,405.0,3056.0,6.0,30.0,61.0,13.0,1560.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,60496,605.0,36.0,21.0,14928.0,22.0,767.0,18.0,4875.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,236582,21.0,3.0,372.0,3123.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [146]:
tweet_sequences = pad_sequences(tweet_sequences , maxlen=57 , padding="post")
pd.DataFrame(tweet_sequences)

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,7,659,19,98,49,596,159,676,112,2523,...,0,0,0,0,0,0,0,0,0,0
1,33414,1,142205,281,455,9,3,11150,1670,2,...,0,0,0,0,0,0,0,0,0,0
2,5,372,771,405,3056,6,30,61,13,1560,...,0,0,0,0,0,0,0,0,0,0
3,60496,605,36,21,14928,22,767,18,4875,95,...,0,0,0,0,0,0,0,0,0,0
4,236582,21,3,372,3123,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048567,5,2040,7,314,836474,25,5,789,0,0,...,0,0,0,0,0,0,0,0,0,0
1048568,44328,5126,2097,4,3083,12,1460,18854,8410,0,...,0,0,0,0,0,0,0,0,0,0
1048569,836475,239,104,188,11,30,45,3,836476,4338,...,0,0,0,0,0,0,0,0,0,0
1048570,78493,47,130,100005,836477,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048571,128,163,509,100,993,26,208,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [147]:
vocab_tweet_size = len(tk.word_index)+1
vocab_tweet_size

836478

## bild model

In [149]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN , Dense

In [216]:
num_classes = len(set(data_train_label))
num_classes

2

In [230]:
model = Sequential([
    Embedding(input_dim=vocab_tweet_size , output_dim=128 , input_length=57 ),
    SimpleRNN(64, activation='tanh'),
    Dense(2 , activation='softmax')
])

C:\Users\hawra\Downloads\anaconda\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [236]:
max_len = 57
model.build(input_shape=(None , max_len))

In [234]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [153]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 57, 128)        │   107,069,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 64)             │        12,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 107,081,731 (408.48 MB)

 Trainable params: 107,081,731 (408.48 MB)

 Non-trainable params: 0 (0.00 B)

In [186]:
import numpy as np
tweet_sequences = np.array(tweet_sequences)
data_train_label = np.array(data_train_label)

In [246]:
data_train_label = np.where(data_train_label == 4, 1, data_train_label)

In [ ]:
history = model.fit(tweet_sequences , data_train_label, batch_size=36 , epochs=20, validation_split=0.2)

Epoch 1/20
  463/23302 ━━━━━━━━━━━━━━━━━━━━ 5:58:55 943ms/step - accuracy: 0.9492 - loss: 0.2009

array(['0', '0', '0', ..., '4', '4', '4'], dtype='<U1')

In [200]:
data_train_label = data_train_label.astype(int)

In [204]:
tweet_sequences.shape

(1048572, 57)

In [206]:
data_train_label.shape

(1048572,)

In [208]:
data_train_label.dtype

dtype('int32')

In [210]:
print(type(tweet_sequences))
print(type(data_train_label))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>